package com.noah.dianping.dal;

import com.noah.dianping.model.ShopModel;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.List;

@Repository
public interface ShopModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Thu Jan 14 16:57:07 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Thu Jan 14 16:57:07 CST 2021
     */
    int insert(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Thu Jan 14 16:57:07 CST 2021
     */
    int insertSelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Thu Jan 14 16:57:07 CST 2021
     */
    ShopModel selectByPrimaryKey(Integer id);

    List<ShopModel> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Thu Jan 14 16:57:07 CST 2021
     */
    int updateByPrimaryKeySelective(ShopModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbg.generated Thu Jan 14 16:57:07 CST 2021
     */
    int updateByPrimaryKey(ShopModel record);

    Integer countAllShop();

    List<ShopModel> recommend(@Param("longitude") BigDecimal longitude,@Param("latitude") BigDecimal latitude);

}